project_id = "idupowkqzcwrjslcixsp"

[functions.voice-incoming]
verify_jwt = false

[functions.sms-webhook] 
verify_jwt = false

[functions.get-call-logs]
verify_jwt = false

[functions.test-openai]
verify_jwt = false

[functions.test-twilio]
verify_jwt = false

[functions.test-calcom]
verify_jwt = false

[functions.send-call-notification]
verify_jwt = false

[functions.cleanup-recordings]
verify_jwt = false

[functions.send-digest-emails]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.grant-super-user]
verify_jwt = false

[functions.configure-twilio-recording]
verify_jwt = false

[functions.call-status-webhook]
verify_jwt = false