# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
# "lov-actions.md" = "selected"
# "vite.config.ts" = "selected"
# "tailwind.config.ts" = "selected"
# "index.html" = "selected"
# "tsconfig.node.json" = "selected"
# "tsconfig.json" = "selected"
# "package-lock.json" = "selected"
# "tsconfig.app.json" = "selected"
# "README.md" = "selected"
# "bun.lockb" = "selected"
# "eslint.config.js" = "selected"
# "components.json" = "selected"
# "postcss.config.js" = "selected"
# "package.json" = "selected"
# "public/placeholder.svg" = "selected"
# "public/robots.txt" = "selected"
# "public/favicon.ico" = "selected"
# "src/vite-env.d.ts" = "selected"
# "src/App.css" = "selected"
# "src/main.tsx" = "selected"
# "src/App.tsx" = "selected"
# "src/index.css" = "selected"
# "supabase/config.toml" = "selected"
# "src/hooks/usePlanEnforcement.tsx" = "selected"
# "src/hooks/use-toast.ts" = "selected"
# "src/hooks/use-mobile.tsx" = "selected"
# "src/components/PremiumFeaturesNav.tsx" = "selected"
# "src/components/SubscriptionTester.tsx" = "selected"
# "src/components/BackfillCollectedData.tsx" = "selected"
# "src/components/UsageOverview.tsx" = "selected"
# "src/components/AppSidebar.tsx" = "selected"
# "src/components/TwilioManagement.tsx" = "selected"
# "src/components/SystemPromptManagement.tsx" = "selected"
# "src/components/GrantSuperUser.tsx" = "selected"
# "src/pages/CallDetails.tsx" = "selected"
# "src/pages/Index.tsx" = "selected"
# "src/pages/Integrations.tsx" = "selected"
# "src/pages/APIsManagement.tsx" = "selected"
# "src/pages/Auth.tsx" = "selected"
# "src/pages/AssistantSettings.tsx" = "selected"
# "src/pages/NotFound.tsx" = "selected"
# "src/pages/CustomerContacts.tsx" = "selected"
# "src/pages/PlanManagement.tsx" = "selected"
# "src/pages/Security.tsx" = "selected"
# "src/pages/SpecificCallDetails.tsx" = "selected"
# "src/pages/PremiumFeatures.tsx" = "selected"
# "src/pages/SuperUserDashboard.tsx" = "selected"
# "src/lib/utils.ts" = "selected"
# "src/lib/currency.ts" = "selected"
# "src/contexts/AuthContext.tsx" = "selected"
# "src/integrations/supabase/client.ts" = "selected"
# "src/integrations/supabase/types.ts" = "selected"
# "src/components/analytics/CallAnalyticsChart.tsx" = "selected"
# "src/components/ui/popover.tsx" = "selected"
# "src/components/ui/table.tsx" = "selected"
# "src/components/ui/accordion.tsx" = "selected"
# "src/components/ui/toaster.tsx" = "selected"
# "src/components/ui/input.tsx" = "selected"
# "src/components/ui/calendar.tsx" = "selected"
# "src/components/ui/breadcrumb.tsx" = "selected"
# "src/components/ui/badge.tsx" = "selected"
# "src/components/ui/avatar.tsx" = "selected"
# "src/components/ui/label.tsx" = "selected"
# "src/components/ui/switch.tsx" = "selected"
# "src/components/ui/scroll-area.tsx" = "selected"
# "src/components/ui/card.tsx" = "selected"
# "src/components/ui/slider.tsx" = "selected"
# "src/components/ui/toggle.tsx" = "selected"
# "src/components/ui/textarea.tsx" = "selected"
# "src/components/ui/hover-card.tsx" = "selected"
# "src/components/ui/form.tsx" = "selected"
# "src/components/ui/sonner.tsx" = "selected"
# "src/components/ui/dropdown-menu.tsx" = "selected"
# "src/components/ui/pagination.tsx" = "selected"
# "src/components/ui/dialog.tsx" = "selected"
# "src/components/ui/skeleton.tsx" = "selected"
# "src/components/ui/tooltip.tsx" = "selected"
# "src/components/ui/toast.tsx" = "selected"
# "src/components/ui/checkbox.tsx" = "selected"
# "src/components/ui/carousel.tsx" = "selected"
# "src/components/ui/context-menu.tsx" = "selected"
# "src/components/ui/input-otp.tsx" = "selected"
# "src/components/ui/menubar.tsx" = "selected"
# "src/components/ui/collapsible.tsx" = "selected"
# "src/components/ui/alert-dialog.tsx" = "selected"
# "src/components/ui/sidebar.tsx" = "selected"
# "src/components/ui/tabs.tsx" = "selected"
# "src/components/ui/drawer.tsx" = "selected"
# "src/components/ui/aspect-ratio.tsx" = "selected"
# "src/components/ui/sheet.tsx" = "selected"
# "src/components/ui/navigation-menu.tsx" = "selected"
# "src/components/ui/button.tsx" = "selected"
# "src/components/ui/use-toast.ts" = "selected"
# "src/components/ui/resizable.tsx" = "selected"
# "src/components/ui/progress.tsx" = "selected"
# "src/components/ui/alert.tsx" = "selected"
# "src/components/ui/select.tsx" = "selected"
# "src/components/ui/toggle-group.tsx" = "selected"
# "src/components/ui/command.tsx" = "selected"
# "src/components/ui/separator.tsx" = "selected"
# "src/components/ui/radio-group.tsx" = "selected"
# "src/components/ui/chart.tsx" = "selected"
# "src/components/dashboard/ApiKeySetupModal.tsx" = "selected"
# "src/components/dashboard/UserDetailsModal.tsx" = "selected"
# "src/components/dashboard/UserPlanManager.tsx" = "selected"
# "supabase/migrations/20250713110004-a9c8279a-1bb8-4cfd-bd16-1cdfbc388bad.sql" = "selected"
# "supabase/migrations/20250713110234-cd32e270-d775-43fd-a7d5-d383800756f1.sql" = "selected"
# "supabase/migrations/20250708100121-63d78d89-dd92-4174-8e6b-6c69eff78c2c.sql" = "selected"
# "supabase/migrations/20250709141250-60257068-4c4b-4924-b144-89d6e3ae5122.sql" = "selected"
# "supabase/migrations/20250710172519-cb4f5632-fc4d-43e0-9526-62ba0bce3ed2.sql" = "selected"
# "supabase/migrations/20250708085934-b86938ea-336e-4c04-a562-d7eb7c373298.sql" = "selected"
# "supabase/migrations/20250713110300-a115e15f-784b-486f-8743-2dc12b813300.sql" = "selected"
# "supabase/migrations/20250709151304-3f5d5037-6301-4309-b45d-ee381351b1d4.sql" = "selected"
# "supabase/migrations/20250708085012-45a99eaa-f77c-42cd-b80e-b48af43c5a4a.sql" = "selected"
# "supabase/migrations/20250708091253-6e506abb-d6eb-4f82-86ca-cb1dbd6c5f03.sql" = "selected"
# "supabase/migrations/20250709142335-7324c252-fc73-43fb-b912-2ff0ecc44f6c.sql" = "selected"
# "supabase/migrations/20250707151238-fd6845ed-9d57-4d0d-954a-92b538e6411c.sql" = "selected"
# "supabase/migrations/20250708084607-e4e482f9-84b7-431b-a523-86473cf688ad.sql" = "selected"
# "supabase/migrations/20250708100022-4cc57977-2222-40e5-b56e-1225952c5916.sql" = "selected"
# "supabase/migrations/20250708082509-6aa49eb4-835e-43c1-80c4-9604939d1d5a.sql" = "selected"
# "supabase/migrations/20250707120226-364b1a9b-07bf-4b3c-98c1-18f3adb4744c.sql" = "selected"
# "supabase/migrations/20250708091045-9c2dbbaf-2ed9-4682-a1b4-2929282d4296.sql" = "selected"
# "supabase/migrations/20250708100644-58eecece-53fa-4d73-af92-3b258cebe171.sql" = "selected"
# "supabase/migrations/20250708083346-d43a2a3f-4489-4792-8148-951f1faa606d.sql" = "selected"
# "supabase/migrations/20250710184152-9ea4c40c-928f-4e53-bfb0-ef2d00e7b684.sql" = "selected"
# "supabase/migrations/20250710175142-f80be1da-f51c-49a8-a07a-02997b1e6489.sql" = "selected"
# "supabase/migrations/20250709145341-f702ffd7-2284-4602-a435-fe1dabf9d26d.sql" = "selected"
# "supabase/migrations/20250713110029-15e3eebb-9958-46f3-aff3-12ca682de66d.sql" = "selected"
# "supabase/migrations/20250710163729-fa3258ad-2a4a-439b-bdf7-974f356746b9.sql" = "selected"
# "supabase/migrations/20250708093740-b944649e-5413-4acb-bcbf-ac6a02de32ac.sql" = "selected"
# "supabase/migrations/20250707151405-9f264b41-3b25-496a-8e26-1113b74dda22.sql" = "selected"
# "supabase/migrations/20250710184356-efb00127-7850-4852-98b4-118338d80ff1.sql" = "selected"
# "supabase/migrations/20250709150327-42f667a8-641a-47b8-882f-577f6b52ea31.sql" = "selected"
# "supabase/functions/send-digest-emails/index.ts" = "selected"
# "supabase/functions/test-stripe/index.ts" = "selected"
# "supabase/functions/ai-call-handler/index.ts" = "selected"
# "supabase/functions/get-api-key/index.ts" = "selected"
# "supabase/functions/configure-twilio-recording/index.ts" = "selected"
# "supabase/functions/transcribe-audio/index.ts" = "selected"
# "supabase/functions/test-calcom/index.ts" = "selected"
# "supabase/functions/test-email-notification/index.ts" = "selected"
# "supabase/functions/send-call-notification/index.ts" = "selected"
# "supabase/functions/test-twilio/index.ts" = "selected"
# "supabase/functions/test-twilio-call/index.ts" = "selected"
# "supabase/functions/test-openai/index.ts" = "selected"
# "supabase/functions/call-routing/index.ts" = "selected"
# "supabase/functions/translate-text/index.ts" = "selected"
# "supabase/functions/crm-integration/index.ts" = "selected"
# "supabase/functions/create-checkout/index.ts" = "selected"
# "supabase/functions/get-call-logs/index.ts" = "selected"
# "supabase/functions/manage-user-plan/index.ts" = "selected"
# "supabase/functions/voice-incoming/index.ts" = "selected"
# "supabase/functions/grant-super-user-with-password/index.ts" = "selected"
# "supabase/functions/get-user-details/index.ts" = "selected"
# "supabase/functions/test-elevenlabs-tts/index.ts" = "selected"
# "supabase/functions/backfill-collected-data/index.ts" = "selected"
# "supabase/functions/sms-webhook/index.ts" = "selected"
# "supabase/functions/admin-analytics/index.ts" = "selected"
# "supabase/functions/customer-portal/index.ts" = "selected"
# "supabase/functions/cleanup-recordings/index.ts" = "selected"
# "supabase/functions/grant-super-user/index.ts" = "selected"
# "supabase/functions/check-subscription/index.ts" = "selected"
# "supabase/functions/call-status-webhook/index.ts" = "selected"
# "supabase/functions/send-notification/index.ts" = "selected"
# "supabase/functions/test-elevenlabs/index.ts" = "selected"
# "supabase/functions/configure-twilio-webhook/index.ts" = "selected"
